### ISSUE TITLE
Flex layout schema missing values

### ISSUE THREAD

**Issue by chemedev** [agencia-e-plus/vtex-io-intelisense#22]
Hi guys,

Found that `horizontalAlign` prop in flex-layout.row is missing `between` and `around` values and `colJustify` is missing `left`, `right` and `center`. You can check this here: https://github.com/vtex-apps/flex-layout/blob/master/react/Row.tsx

ps: If it helps, I can send a PR whenever I found this kind of minor schema issues, just tell me how you want me to do it :)

**Comment by IncognitaDev** [comment]
Thanks for open the Issue,

its already fixed, will be available in some minutes. I thinks the issues are perfectly to this cases, but if you want to contribute directly with PRs I will create a Contribution.md and a step to show how the autocomplete wortks, then you be able to make your own changes.
