### ISSUE TITLE
No componente store-image falta o Intellisense para o Analytics.

### ISSUE THREAD

**Issue by zeluizr** [agencia-e-plus/vtex-io-intelisense#25]
No componente store-image falta o autocomplete para os parametros do Analytics.

```   
  "image#half-banner": {
    "title": "Banner Image",
    "props": {
      "blockClass": "half-banner",
      "src": "https://tpc.googlesyndication.com/simgad/4650874776646813218?",
      "link": {
        "url": "/"
      },
      "analyticsProperties": "provide",
      "promotionId": "HALF_BANNER",
      "promotionName": "Half Banner",
      "promotionPosition": "halfbanner"
    }
  }
```

**Comment by IncognitaDev** [comment]
thanks for open this issue

I dont knew of this properties since they are not in vtex documentation, I'll fix it.

**Comment by IncognitaDev** [comment]
Opa, desculpa por responder em inglês, foi automático.

Prontinho, a correção foi aplicada, sua extensão deve atualizar em breve.  

Qualquer outro problema, sinta-se à-vontade para abrir outras issues.
