### ISSUE TITLE
search-result-layout não mostra Children

### ISSUE THREAD

**Issue by zeluizr** [agencia-e-plus/vtex-io-intelisense#26]
No autocomplete de `search-result-layout` não mostra o `children`.

Na verdade mostra `blocks`, que no caso está errado.

Como está:
```
"search-result-layout.desktop": {
    "blocks": ["flex-layout.row#breadcrumb", "flex-layout.row#content"],
},
  ```
  Como deveria ser:
  ```
"search-result-layout.desktop": {
    "children": ["flex-layout.row#breadcrumb", "flex-layout.row#content"],
},
  ```
  
  Muito obrigado, estou gostando muito do Plugin. 🤘

**Comment by IncognitaDev** [comment]
Que bom que esta gostando da plugin.

Corrigido, deve atualizar em alguns minutos.
