### ISSUE TITLE
Autocomplete de `` não funciona.

### ISSUE THREAD

**Issue by zeluizr** [agencia-e-plus/vtex-io-intelisense#29]
Olá,

O autocomplete para o componente `"product-summary-price"` não está autocompletando.

ref: https://developers.vtex.com/docs/guides/vtex-product-summary-productsummaryprice

Thanx! 🤘

**Comment by IncognitaDev** [comment]
Não fizemos o autocomplete desse app ja que ele esta depreciado pela vtex.

**Comment by zeluizr** [comment]
Não sabia disso! Muito obrigado pela info! 🤘
