### ISSUE TITLE
iconProps not allowed

### ISSUE THREAD

**Issue by zeluizr** [agencia-e-plus/vtex-io-intelisense#30]
Oi,

No autocompletado sai que iconPros é "not allowed", porém ele sim faz parte da documentação.
Fui olhar a documentação e não mostra nada deprecated: https://developers.vtex.com/docs/guides/vtex-menu

Outra pergunta, esse projeto está open-source? porque gostaria de adicionar função das apps que tenho.

Abrs.,

**Comment by IncognitaDev** [comment]
Olá,

Ah sim, vou corrigir esse problema do auto complete.

Sim o projeto é open source, porem não permitimos a adição de autocomplete de apps privados na extensão, estamos trabalhando em permitir que cada utilizador possa ter uma biblioteca pessoal de autocomplete, mas isso é uma feature futura.

**Comment by zeluizr** [comment]
Oi @IncognitaDev, tudo bem?

Sabe quando se vai consertar esse issue?

Seria possivel, eu fazer um Pull Request, com isso nos ajudamos? 😬

<img width="633" alt="Captura de pantalla 2023-11-23 a la(s) 17 33 03" src="https://github.com/agencia-e-plus/vtex-io-intelisense/assets/1095908/d7f84063-bf6a-4fd0-a07a-fb6ab3d0e5e6">

**Comment by jrodrigues-webimpacto** [comment]
Oi @IncognitaDev,

Isso seria muito bom, porque dá erro no VS Code direto por isso.
Eu também posso ajudar para contribuir no repo. 😉

Att.,

**Comment by IncognitaDev** [comment]
Oi Pessoal, 

Tive um problema com o workflow de deploy, vou corrigir e aviso vocês.
