### ISSUE TITLE
blockClass schema error

### ISSUE THREAD

**Issue by diieen** [agencia-e-plus/vtex-io-intelisense#36]
Após a última atualização, os arquivos json dos blocos começaram a apresentar problemas de sintaxe.

![image](https://github.com/agencia-e-plus/vtex-io-intelisense/assets/69799169/7fdb092c-14bb-4def-9ee0-d78bd15d3272)

![image](https://github.com/agencia-e-plus/vtex-io-intelisense/assets/69799169/5ff3d0d2-01aa-4dce-8203-799c5de10ea8)

Não sei se tem alguma coisa a ver, mas utilizo o VS Code Insiders. O problema ocorre em todos os arquivos JSON da loja.

**Comment by IncognitaDev** [comment]
Obrigado pela issue, já estamos corrigindo.

**Comment by IncognitaDev** [comment]
Corrigido na versão 1.5.2
